services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back
    volumes:
      - ./results:/app/results
    networks:
      - my_network
    expose:
      - "8001"
    ports:
      - "8001:8001"


  frontend:
    image: nginx:alpine
    container_name: front
    ports:
      - "8000:8000"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./results:/usr/share/nginx/results
    networks:
      - my_network
    depends_on:
      - backend

networks:
  my_network:
    driver: bridge